### ISSUE TITLE
Hitting shellout timeout after 600 secs

### ISSUE THREAD

**Issue by arielrolfo** [chef-cookbooks/delivery-sugar#43]
I've been facing this when I run complex tf plans using openstack resources:
```
Mixlib::ShellOut::CommandTimeout: delivery_terraform[terraform-plan union] (ibm_build::provision line 93) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
Command exceeded allowed execution time, process terminated
```
@jeremymv2

**Comment by sean-horn** [comment]
```
chef > shell_out!("sleep 12", cwd: "/tmp", live_stream: STDOUT, timeout: 10)
Mixlib::ShellOut::CommandTimeout: Command timed out after 10s:
Command exceeded allowed execution time, process terminated
---- Begin output of sleep 12 ----
STDOUT:
STDERR:
---- End output of sleep 12 ----
Ran sleep 12 returned
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout/unix.rb:124:in `run_command'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:259:in `run_command'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/shell_out.rb:191:in `shell_out_command'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/shell_out.rb:112:in `shell_out'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/shell_out.rb:117:in `shell_out!'
    from (irb):10
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/shell.rb:75:in `block in start'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/shell.rb:74:in `catch'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/shell.rb:74:in `start'
    from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/bin/chef-shell:34:in `<top (required)>'
    from /opt/opscode/embedded/bin/chef-shell:22:in `load'
    from /opt/opscode/embedded/bin/chef-shell:22:in `<main>'
```

Could be adjusted in the same way at https://github.com/chef-cookbooks/delivery-sugar/blob/master/resources/delivery_terraform.rb#L76

**Comment by jeremymv2** [comment]
@arielrolfo this has been resolved by https://github.com/chef-cookbooks/delivery-sugar/commit/f7f33c751401be51316a51fef2db31b6a0907cbb
